# Generated by Django 5.0.2 on 2024-09-01 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('route', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='SizeGender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'size_gender',
            },
        ),
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'size_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('state', models.CharField(choices=[('Creado', 'created'), ('Disponible', 'available'), ('No Disponible', 'not_available'), ('Sin Inventario', 'out_of_stoke')], default='CREATED', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.size')),
                ('sizeGender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.sizegender')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='PrudctoImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.product')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.images')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.AddField(
            model_name='size',
            name='sizeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.sizetype'),
        ),
        migrations.AddField(
            model_name='category',
            name='sizeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.sizetype'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
