# Generated by Django 5.0.2 on 2024-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('Creado', 'created'), ('Disponible', 'available'), ('No Disponible', 'not_available'), ('Sin Inventario', 'out_of_stoke')], default='Creado', max_length=20),
        ),
    ]
