# Generated by Django 5.0.2 on 2024-09-01 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('firstName', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25, null=True)),
                ('lastName', models.CharField(max_length=25)),
                ('surName', models.CharField(max_length=25, null=True)),
                ('documentNumber', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('documentType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.documenttype')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('cellphone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.person')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.role')),
            ],
            options={
                'db_table': 'person_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changePassword', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.person')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
